# Chapter 4: NumPy and Pandas

## NumPy

## Arrays vs Lists

In [3]:
import numpy as np

In [70]:
import numpy as np
l = [1,2,3]
a = np.array([1,2,3])
print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [71]:
for i in l:
    print(i)
print('---------')
for i in a:
    print(i)

1
2
3
---------
1
2
3


In [72]:
print(l+[4])
print(a+np.array(4))
print('------')
print(2*a)
print(2*l)

[1, 2, 3, 4]
[5 6 7]
------
[2 4 6]
[1, 2, 3, 1, 2, 3]


In [67]:
l2 = []
for e in l:
    l2.append(e**2)
print(l2)
print(a**2)

[1, 4, 9]
[1 4 9]


In [18]:
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.tanh(a))

[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.76159416 0.96402758 0.99505475]


# Matrices 2D

In [88]:
import numpy as np
l = [[1,2,3],[4,5,6]] 
print(l)
n = np.array(l)
print(n)


[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


## Matrice index

In [89]:
#Selecting the number form first row of second column
print(l[0][1])
print(n[0][1])
print(n[0,1])

# Selecting first column 
print(n[:,0])
# Selecting First row
print(n[0,:])

2
2
2
[1 4]
[1 2 3]


## Matrice Operations

In [95]:
n = np.array([[1,2,3],[4,5,6]] )
# transpose of matrix
print(n.T)
print('---------')
# natural exponential function
print(np.exp(n))

[[1 4]
 [2 5]
 [3 6]]
---------
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [91]:
print(np.exp([[1,2,3],[4,5,6]] )) #List treated as numpy array

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [97]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) #Shape(2X3)
b = np.array([[1,2],[3,4],[5,6]])#Shape(3X2)
print(a.dot(b)) # dot product

[[22 28]
 [49 64]]


In [35]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) #Shape(2X3)
b = np.array([[1,2],[3,4]])#Shape(2X2)
print(a.dot(b)) # dot product

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [48]:
import numpy as np
a = np.array([[5,6],[7,8]]) #Shape(2X2)
# Matrice determinant
print(np.linalg.det(a))
# Matrice inverse
print(np.linalg.inv(a))

-1.999999999999999
[[-4.   3. ]
 [ 3.5 -2.5]]


In [92]:
#Checking the inverse
a = np.array([[5,6],[7,8]])
print(np.linalg.inv(a).dot(a))

[[ 1.00000000e+00  0.00000000e+00]
 [-3.55271368e-15  1.00000000e+00]]


In [115]:
## Solving linear equations
#−3𝑥 − 2𝑦 + 4𝑧 = 9
#3𝑦 − 2𝑧 = 5
#4𝑥− 3𝑦 + 2𝑧 = 7


a = np.array([[-3,-2,4],[0,3,-2],[4,-3,2]])
b = np.array([9,5,7])
print(np.linalg.inv(a).dot(b))


[3. 7. 8.]


In [116]:
print(np.linalg.solve(a,b))

[3. 7. 8.]


## Comparing matrice

In [55]:
## Camparing matrice
a = np.array([[1,2],[4,6]]) #Shape(2X2)
b = np.array([[1,2],[3,4]])#Shape(2X2)
c = np.array([[1,2],[4,6]]) #Shape(2X2)

print(a==b)
print(a==c)

print('-------------')

print(np.allclose(a,b))
print(np.allclose(a,c))


[[ True  True]
 [False False]]
[[ True  True]
 [ True  True]]
-------------
False
True


## Genarating data

In [74]:
print(np.zeros((2,3)))
print('------------')
print(np.ones((2,3)))
print('------------')
print(10*np.ones((2,3)))
print('------------')
print(np.eye(3))# Identity matrices

[[0. 0. 0.]
 [0. 0. 0.]]
------------
[[1. 1. 1.]
 [1. 1. 1.]]
------------
[[10. 10. 10.]
 [10. 10. 10.]]
------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
print(np.random.random())
print('------------')
print(np.random.random((2,3)))
print('------------')
print(np.random.randn(2,3))

0.7420709390526112
------------
[[0.64231956 0.27470495 0.83306675]
 [0.62637418 0.870846   0.10071372]]
------------
[[-0.85548405  0.94454349 -0.09391225]
 [ 0.27754079 -0.92784648 -0.56905913]]


In [70]:
r = np.random.randn(10000)
print(r.mean())
print(r.var())
print(r.std())

0.0019385521899210887
0.9913490868162517
0.9956651479369214


In [76]:
r = np.random.randn(10000,3)
print(r.mean(axis=0))
print(np.shape(r.mean(axis=1)))
print(np.cov(r).shape)
print(np.cov(r.T))

[ 0.01201891 -0.0108183   0.01162437]
(10000,)
(10000, 10000)
[[ 0.9977255  -0.00311307  0.00287144]
 [-0.00311307  1.00920042  0.00454251]
 [ 0.00287144  0.00454251  0.99319944]]


In [77]:
#generating interger
print(np.random.randint(0,10,size=(3,3)))

[[5 5 7]
 [5 9 7]
 [2 5 7]]


In [78]:
print(np.random.choice(10,size=(3,3)))

[[4 6 4]
 [2 7 1]
 [6 1 1]]


## Speed Test

In [86]:
from datetime import datetime

a = np.random.rand(100)
b = np.random.rand(100)
T = 100000
def slow_dot_product(a,b):
    result = 0
    for e,f in zip(a,b):
        result += e*f
    return result

t0 = datetime.now()
for t in range(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
    np.dot(a,b)
dt2 = datetime.now() - t0

print("d1 / dt2:",dt1.total_seconds()/
     dt2.total_seconds())


d1 / dt2: 34.875979378699014


# Pandas

## Loading in Data

In [117]:
import pandas as pd
df =  pd.read_csv('datasets.csv')
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [7]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [8]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 768 non-null int64
Glucose                     768 non-null int64
BloodPressure               768 non-null int64
SkinThickness               768 non-null int64
Insulin                     768 non-null int64
BMI                         768 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null int64
Outcome                     768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


## Selecting Rows and Columns

In [119]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [127]:
df.columns = ['Pregnancies', 'Glucose', 'BP', 'ST', 'Insulin',
       'BMI', 'DPF', 'Age', 'Outcome']
df.head()

Pregnancies  Glucose  BP  ST  Insulin   BMI    DPF  Age  Outcome
0            6      148  72  35        0  33.6  0.627   50        1
1            1       85  66  29        0  26.6  0.351   31        0
2            8      183  64   0        0  23.3  0.672   32        1
3            1       89  66  23       94  28.1  0.167   21        0
4            0      137  40  35      168  43.1  2.288   33        1

In [17]:
#Selecting Columns
print(df['Glucose'])
print(type(df['Glucose']))


0      148
1       85
2      183
3       89
4      137
      ... 
763    101
764    122
765    121
766    126
767     93
Name: Glucose, Length: 768, dtype: int64
<class 'pandas.core.series.Series'>


In [122]:
print(df[['Glucose','Insulin']])
print(type(df[['Glucose','Insulin']]))


     Glucose  Insulin
0        148        0
1         85        0
2        183        0
3         89       94
4        137      168
..       ...      ...
763      101      180
764      122        0
765      121      112
766      126        0
767       93        0

[768 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>


In [147]:
#Selecting Rows
print(df.iloc[0]) #intiger index argumnets
print(type(df.iloc[0]))
print('\n-------\n')
print(df.iloc[0:2])#selecting two rows
print(type(df.iloc[0:2]))
print('\n-------\n')
print(df.iloc[0:2]['Glucose'])#selecting values in rows

Pregnancies      6.000
Glucose        148.000
BP              72.000
ST              35.000
Insulin          0.000
BMI             33.600
DPF              0.627
Age             50.000
Outcome          1.000
Name: 0, dtype: float64
<class 'pandas.core.series.Series'>

-------

   Pregnancies  Glucose  BP  ST  Insulin   BMI    DPF  Age  Outcome
0            6      148  72  35        0  33.6  0.627   50        1
1            1       85  66  29        0  26.6  0.351   31        0
<class 'pandas.core.frame.DataFrame'>

-------

0    148
1     85
Name: Glucose, dtype: int64


In [144]:
df[df['BP']>110]

Pregnancies  Glucose   BP  ST  Insulin   BMI    DPF  Age  Outcome
106            1       96  122   0        0  22.4  0.207   27        0
691           13      158  114   0        0  42.3  0.257   44        1

In [130]:
df['BP']>110


0      False
1      False
2      False
3      False
4      False
       ...  
763    False
764    False
765    False
766    False
767    False
Name: BP, Length: 768, dtype: bool

In [149]:
print(df.values)
print(type(df.values))
print(np.shape(df.values))

[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
<class 'numpy.ndarray'>
(768, 9)


In [81]:
new_df = df[['Glucose','Insulin','BP']]
new_df.to_csv('small_dataset.csv')
with open('small_dataset.csv') as f:
    data = f.read()
print(data[:52])
print('-------------')
# getiing rd of index column
new_df.to_csv('small_dataset.csv',index=False)
with open('small_dataset.csv') as f:
    data = f.read()
print(data[:54])

,Glucose,Insulin,BP
0,148,0,72
1,85,0,66
2,183,0,64

-------------
Glucose,Insulin,BP
148,0,72
85,0,66
183,0,64
89,94,66



## apply() function

In [40]:
def age_to_category(age):
    if age<18:
        return 'young'
    if age>=18 and age<=55:
        return 'middle-age'
    if age>55:
        return 'aged'
age = df['Age']
age.apply(age_to_category)

0      middle-age
1      middle-age
2      middle-age
3      middle-age
4      middle-age
          ...    
763          aged
764    middle-age
765    middle-age
766    middle-age
767    middle-age
Name: Age, Length: 768, dtype: object

In [41]:
df['Age_cat']=age.apply(age_to_category)
df.head()

Pregnancies  Glucose  BP  ST  Insulin   BMI    DPF  Age  Outcome  \
0            6      148  72  35        0  33.6  0.627   50        1   
1            1       85  66  29        0  26.6  0.351   31        0   
2            8      183  64   0        0  23.3  0.672   32        1   
3            1       89  66  23       94  28.1  0.167   21        0   
4            0      137  40  35      168  43.1  2.288   33        1   

      Age_cat  
0  middle-age  
1  middle-age  
2  middle-age  
3  middle-age  
4  middle-age

## Concatenating and Merging

In [152]:
df1 = df[['Glucose','BP','ST']]
print(df1.head())
df2 = df[['Pregnancies','Insulin','BMI']]
print(df2.head())
concat_df=pd.concat([df1,df2],sort=False,axis=1)
concat_df.head()

   Glucose  BP  ST
0      148  72  35
1       85  66  29
2      183  64   0
3       89  66  23
4      137  40  35
   Pregnancies  Insulin   BMI
0            6        0  33.6
1            1        0  26.6
2            8        0  23.3
3            1       94  28.1
4            0      168  43.1


Glucose  BP  ST  Pregnancies  Insulin   BMI
0      148  72  35            6        0  33.6
1       85  66  29            1        0  26.6
2      183  64   0            8        0  23.3
3       89  66  23            1       94  28.1
4      137  40  35            0      168  43.1

In [153]:
# Mergeing data tables
expression = pd.read_csv('expression.csv')
print(expression.head())
print('\n\n')
annotation = pd.read_csv('annotation.csv')
print(annotation.head())
merged_table = pd.merge(annotation,expression,on='ID')
merged_table.head()

             ID     logFC   P.Value
0  ILMN_1812297  2.887204  0.000011
1  ILMN_2392803  2.587258  0.000047
2  ILMN_1730612 -1.892913  0.000077
3  ILMN_1780349  2.618084  0.000082
4  ILMN_1677636  2.890289  0.000088



             ID Gene.symbol                                         Gene.title
0  ILMN_1812297     CYP26B1     cytochrome P450 family 26 subfamily B member 1
1  ILMN_2392803     COL11A1                     collagen type XI alpha 1 chain
2  ILMN_1730612      DBNDD2                      dysbindin domain containing 2
3  ILMN_1780349         TPR  translocated promoter region, nuclear basket p...
4  ILMN_1677636        COMP                cartilage oligomeric matrix protein


ID Gene.symbol  \
0  ILMN_1812297     CYP26B1   
1  ILMN_2392803     COL11A1   
2  ILMN_1730612      DBNDD2   
3  ILMN_1780349         TPR   
4  ILMN_1677636        COMP   

                                          Gene.title     logFC   P.Value  
0     cytochrome P450 family 26 subfamily B member 1  2.887204  0.000011  
1                     collagen type XI alpha 1 chain  2.587258  0.000047  
2                      dysbindin domain containing 2 -1.892913  0.000077  
3  translocated promoter region, nuclear basket p...  2.618084  0.000082  
4                cartilage oligomeric matrix protein  2.890289  0.000088

## Exercise:
<ol>
<li>Why Numpy is preferred over Python's nested list for multidimensional arrays.</li>
<li>Use NumPy to generate two arrays with shapes (100x6) and (6X1) of random numbers sampled from a standard normal distribution.</li>
<li>Perform matrix operations like transpose and multiplications with the generated arrays.</li>
<li>Apply simple statistic operations on the array of shape &lsquo;100x6&rsquo;.</li>
<li>Import &lsquo;pandas&rsquo; and open the &lsquo;heart.csv&rsquo; files supplied in the supplementary file.</li>
<li>Check the head of the above data frame DataFrame and grab the column names.</li>
<li>Select the columns with name and find the mean using &lsquo;.mean()&rsquo; function for every column.</li>
<li>&nbsp;Use &lsquo;iloc[]&rsquo; on the DataFrame to select all the columns except the last one.</li>
<li>The 2<sup>nd</sup> column i.e. the column named &lsquo;sex&rsquo; has &lsquo;1&rsquo; for males and &lsquo;0&rsquo; for females. Use the apply method in the to change map &lsquo;1&rsquo; as &lsquo;male&rsquo; and &lsquo;0&rsquo; as &lsquo;female&rsquo;.</li>
</ol>